

export const metadata = {
  title: "Product page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main style={{ padding: "10px" }}>
      <div style={{ display: "flex", padding: "10px" }}>
        <h1>List of Products</h1>
      </div>
      <div>
        {children}
      </div>
    </main>
  );
}
